name: GHA Linter and FortiDevSec
run-name: GH Action to run Linter and FortiDevSec
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  TEAR_DOWN: no
  RUN_LINTER: false

jobs:
  Run-Linter:
    runs-on: self-hosted
    steps:
      - run: echo "Event name is ${{ github.event_name }}."
      - run: echo "Server type is ${{ runner.os }}."
      - run: echo "Branch is ${{ github.ref }}, repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Get submodules
        run: git submodule update --init 
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Run linter
        if: ${{ env.RUN_LINTER == 'true' }}
        run: |
          cfn-lint ${{ github.workspace }}/cloudformation/*.yml
      - run: echo "Job Status is ${{ job.status }}."
  Run-FortiDevSec:
    runs-on: self-hosted
    needs: Run-Linter
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Get submodules
        run: git submodule update --init
      - run: |
          env | grep -E "GITHUB_ACTIONS|GITHUB_RUN_NUMBER|GITHUB_REF_NAME|GITHUB_SHA" > /tmp/env
          docker pull registry.fortidevsec.forticloud.com/fdevsec_sast:latest
          docker run --rm --env-file /tmp/env --mount type=bind,source=$PWD,target=/scan registry.fortidevsec.forticloud.com/fdevsec_sast:latest
